image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - sbt compile

test:
  before_script:
    - apt-get update -qq && apt-get install -y -qq gcc-arm-linux-gnueabi qemu-user-static
  stage: test
  script:
    - sbt test
